# Contributor: Part I {#contributor-I}

## Soft skills
*How do I approach a task?*
What you should be given is clear definition of a task a time frame that you have to fulfill the task. If the task is fairly large, you start by splitting it up to smaller pieces.

Free up your calendar for 3 hours blocks.

When approaching your colleagues, do not approach them with a problem, approach them with what is happening and what you would like to happen. If you are not showing or proposing a solution, you are just complaining. 

*What are legal regulations such as GDPR?*
As you will on this level it will already be expected that you work with a data, it is necessary that you learn a bit about regulations.

*How do I produce a valuable output for my employer?*


## Cloud

What is cloud?
Will I use cloud as a data scientist?
How do I work on cloud?

## Databases and Data Lakes
What is a database?
What is a data lake?

## SQL
What is SQL?
How do I download entire table using SQL?
How do I select columns using SQL?
How do I filter rows using SQL?
How do I join tables in SQL?

## Programming
How do I load data to my IDE?
What types of features do we know?
What is a function?
How do I perform numeric operations in my IDE?

