<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Observer | Authentic Data Science</title>
  <meta name="description" content="This is a book that allows anyone to become a Embedded Data Scientist in an intuitive way." />
  <meta name="generator" content="bookdown 0.16 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Observer | Authentic Data Science" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a book that allows anyone to become a Embedded Data Scientist in an intuitive way." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Observer | Authentic Data Science" />
  
  <meta name="twitter:description" content="This is a book that allows anyone to become a Embedded Data Scientist in an intuitive way." />
  

<meta name="author" content="Robert Barcik" />


<meta name="date" content="2020-03-23" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="being-aware.html"/>
<link rel="next" href="contributor-I.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Becoming Citizen Data Scientist</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Foreword to Authentic Data Science</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#current-state-of-this-book"><i class="fa fa-check"></i><b>1.1</b> Current state of this book</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="being-aware.html"><a href="being-aware.html"><i class="fa fa-check"></i><b>2</b> Being Aware</a><ul>
<li class="chapter" data-level="2.1" data-path="being-aware.html"><a href="being-aware.html#five-cornerstones"><i class="fa fa-check"></i><b>2.1</b> Five Cornerstones</a></li>
<li class="chapter" data-level="2.2" data-path="being-aware.html"><a href="being-aware.html#defining-data-science"><i class="fa fa-check"></i><b>2.2</b> Defining Data Science</a></li>
<li class="chapter" data-level="2.3" data-path="being-aware.html"><a href="being-aware.html#disciplines-of-data-science"><i class="fa fa-check"></i><b>2.3</b> Disciplines of Data Science</a></li>
<li class="chapter" data-level="2.4" data-path="being-aware.html"><a href="being-aware.html#defining-data-scientist"><i class="fa fa-check"></i><b>2.4</b> Defining Data Scientist</a></li>
<li class="chapter" data-level="2.5" data-path="being-aware.html"><a href="being-aware.html#the-struggle-of-data-science"><i class="fa fa-check"></i><b>2.5</b> The Struggle of Data Science</a></li>
<li class="chapter" data-level="2.6" data-path="being-aware.html"><a href="being-aware.html#who-is-embedded-data-scientist"><i class="fa fa-check"></i><b>2.6</b> Who is Embedded Data Scientist</a></li>
<li class="chapter" data-level="2.7" data-path="being-aware.html"><a href="being-aware.html#value-of-embedded-data-scientist"><i class="fa fa-check"></i><b>2.7</b> Value of Embedded Data Scientist</a></li>
<li class="chapter" data-level="2.8" data-path="being-aware.html"><a href="being-aware.html#anyone-can-become-embedded-data-scientist"><i class="fa fa-check"></i><b>2.8</b> Anyone Can Become Embedded Data Scientist</a></li>
<li class="chapter" data-level="2.9" data-path="being-aware.html"><a href="being-aware.html#the-6-levels-of-embedded-data-scientist"><i class="fa fa-check"></i><b>2.9</b> The 6 Levels of Embedded Data Scientist</a></li>
<li class="chapter" data-level="2.10" data-path="being-aware.html"><a href="being-aware.html#real-world-experience"><i class="fa fa-check"></i><b>2.10</b> Real World Experience</a></li>
<li class="chapter" data-level="2.11" data-path="being-aware.html"><a href="being-aware.html#learning-without-math"><i class="fa fa-check"></i><b>2.11</b> Learning Without Math</a></li>
<li class="chapter" data-level="2.12" data-path="being-aware.html"><a href="being-aware.html#population-and-observation"><i class="fa fa-check"></i><b>2.12</b> Population and Observation</a></li>
<li class="chapter" data-level="2.13" data-path="being-aware.html"><a href="being-aware.html#knowing-entire-population"><i class="fa fa-check"></i><b>2.13</b> Knowing Entire Population</a><ul>
<li class="chapter" data-level="2.13.1" data-path="being-aware.html"><a href="being-aware.html#mode-median-and-mean"><i class="fa fa-check"></i><b>2.13.1</b> Mode, Median and Mean</a></li>
</ul></li>
<li class="chapter" data-level="2.14" data-path="being-aware.html"><a href="being-aware.html#not-knowing-entire-population"><i class="fa fa-check"></i><b>2.14</b> Not Knowing Entire Population</a><ul>
<li class="chapter" data-level="2.14.1" data-path="being-aware.html"><a href="being-aware.html#confidence-interval"><i class="fa fa-check"></i><b>2.14.1</b> Confidence Interval</a></li>
</ul></li>
<li class="chapter" data-level="2.15" data-path="being-aware.html"><a href="being-aware.html#predicting-future-values"><i class="fa fa-check"></i><b>2.15</b> Predicting Future Values</a><ul>
<li class="chapter" data-level="2.15.1" data-path="being-aware.html"><a href="being-aware.html#association-rules"><i class="fa fa-check"></i><b>2.15.1</b> Association Rules</a></li>
</ul></li>
<li class="chapter" data-level="2.16" data-path="being-aware.html"><a href="being-aware.html#level-1-being-aware---reached"><i class="fa fa-check"></i><b>2.16</b> Level 1: Being Aware - Reached</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="observer.html"><a href="observer.html"><i class="fa fa-check"></i><b>3</b> Observer</a><ul>
<li class="chapter" data-level="3.1" data-path="observer.html"><a href="observer.html#about-this-level"><i class="fa fa-check"></i><b>3.1</b> About this level</a></li>
<li class="chapter" data-level="3.2" data-path="observer.html"><a href="observer.html#be-skeptical-about-data"><i class="fa fa-check"></i><b>3.2</b> Be Skeptical About Data</a></li>
<li class="chapter" data-level="3.3" data-path="observer.html"><a href="observer.html#data-science-project"><i class="fa fa-check"></i><b>3.3</b> Data Science Project</a></li>
<li class="chapter" data-level="3.4" data-path="observer.html"><a href="observer.html#your-contribution"><i class="fa fa-check"></i><b>3.4</b> Your Contribution</a></li>
<li class="chapter" data-level="3.5" data-path="observer.html"><a href="observer.html#data-and-computing"><i class="fa fa-check"></i><b>3.5</b> Data and Computing</a></li>
<li class="chapter" data-level="3.6" data-path="observer.html"><a href="observer.html#using-data"><i class="fa fa-check"></i><b>3.6</b> Using Data</a><ul>
<li class="chapter" data-level="3.6.1" data-path="observer.html"><a href="observer.html#r"><i class="fa fa-check"></i><b>3.6.1</b> R</a></li>
<li class="chapter" data-level="3.6.2" data-path="observer.html"><a href="observer.html#python"><i class="fa fa-check"></i><b>3.6.2</b> Python</a></li>
<li class="chapter" data-level="3.6.3" data-path="observer.html"><a href="observer.html#knime"><i class="fa fa-check"></i><b>3.6.3</b> Knime</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="observer.html"><a href="observer.html#descriptive-statistics"><i class="fa fa-check"></i><b>3.7</b> Descriptive Statistics</a><ul>
<li class="chapter" data-level="3.7.1" data-path="observer.html"><a href="observer.html#range"><i class="fa fa-check"></i><b>3.7.1</b> Range</a></li>
<li class="chapter" data-level="3.7.2" data-path="observer.html"><a href="observer.html#distributions"><i class="fa fa-check"></i><b>3.7.2</b> Distributions</a></li>
<li class="chapter" data-level="3.7.3" data-path="observer.html"><a href="observer.html#quantiles-percentiles"><i class="fa fa-check"></i><b>3.7.3</b> Quantiles &amp; Percentiles</a></li>
<li class="chapter" data-level="3.7.4" data-path="observer.html"><a href="observer.html#extreme-values-and-outliers"><i class="fa fa-check"></i><b>3.7.4</b> Extreme Values and Outliers</a></li>
<li class="chapter" data-level="3.7.5" data-path="observer.html"><a href="observer.html#percentages"><i class="fa fa-check"></i><b>3.7.5</b> Percentages</a></li>
<li class="chapter" data-level="3.7.6" data-path="observer.html"><a href="observer.html#comparing-distributions"><i class="fa fa-check"></i><b>3.7.6</b> Comparing Distributions</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="observer.html"><a href="observer.html#predicting-the-future"><i class="fa fa-check"></i><b>3.8</b> Predicting The Future?</a></li>
<li class="chapter" data-level="3.9" data-path="observer.html"><a href="observer.html#basics-of-machine-learning"><i class="fa fa-check"></i><b>3.9</b> Basics of Machine Learning</a></li>
<li class="chapter" data-level="3.10" data-path="observer.html"><a href="observer.html#supervised-learning"><i class="fa fa-check"></i><b>3.10</b> Supervised Learning</a></li>
<li class="chapter" data-level="3.11" data-path="observer.html"><a href="observer.html#pitfalls-of-machine-learning"><i class="fa fa-check"></i><b>3.11</b> Pitfalls of Machine Learning</a></li>
<li class="chapter" data-level="3.12" data-path="observer.html"><a href="observer.html#regression"><i class="fa fa-check"></i><b>3.12</b> Regression</a></li>
<li class="chapter" data-level="3.13" data-path="observer.html"><a href="observer.html#classification"><i class="fa fa-check"></i><b>3.13</b> Classification</a></li>
<li class="chapter" data-level="3.14" data-path="observer.html"><a href="observer.html#level-2-reached"><i class="fa fa-check"></i><b>3.14</b> Level 2 Reached</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="contributor-I.html"><a href="contributor-I.html"><i class="fa fa-check"></i><b>4</b> Contributor: Soft Skills</a><ul>
<li class="chapter" data-level="4.1" data-path="contributor-I.html"><a href="contributor-I.html#soft-skills"><i class="fa fa-check"></i><b>4.1</b> Soft skills</a></li>
<li class="chapter" data-level="4.2" data-path="contributor-I.html"><a href="contributor-I.html#project-tasks"><i class="fa fa-check"></i><b>4.2</b> Project &amp; tasks</a></li>
<li class="chapter" data-level="4.3" data-path="contributor-I.html"><a href="contributor-I.html#fitting-into-a-team"><i class="fa fa-check"></i><b>4.3</b> Fitting into a team</a><ul>
<li class="chapter" data-level="4.3.1" data-path="contributor-I.html"><a href="contributor-I.html#kaizen"><i class="fa fa-check"></i><b>4.3.1</b> Kaizen</a></li>
<li class="chapter" data-level="4.3.2" data-path="contributor-I.html"><a href="contributor-I.html#nemawashi"><i class="fa fa-check"></i><b>4.3.2</b> Nemawashi</a></li>
<li class="chapter" data-level="4.3.3" data-path="contributor-I.html"><a href="contributor-I.html#pdca-cycle"><i class="fa fa-check"></i><b>4.3.3</b> PDCA Cycle</a></li>
<li class="chapter" data-level="4.3.4" data-path="contributor-I.html"><a href="contributor-I.html#agile-scrum"><i class="fa fa-check"></i><b>4.3.4</b> Agile &amp; Scrum</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="contributor-I.html"><a href="contributor-I.html#legal-regulations"><i class="fa fa-check"></i><b>4.4</b> Legal regulations</a></li>
<li class="chapter" data-level="4.5" data-path="contributor-I.html"><a href="contributor-I.html#producing-valuable-output"><i class="fa fa-check"></i><b>4.5</b> Producing valuable output</a></li>
<li class="chapter" data-level="4.6" data-path="contributor-I.html"><a href="contributor-I.html#documenting-your-work"><i class="fa fa-check"></i><b>4.6</b> Documenting your work</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="contributor-II.html"><a href="contributor-II.html"><i class="fa fa-check"></i><b>5</b> Contributor: Part II</a><ul>
<li class="chapter" data-level="5.1" data-path="contributor-II.html"><a href="contributor-II.html#cloud"><i class="fa fa-check"></i><b>5.1</b> Cloud</a></li>
<li class="chapter" data-level="5.2" data-path="contributor-II.html"><a href="contributor-II.html#databases-and-data-lakes"><i class="fa fa-check"></i><b>5.2</b> Databases and Data Lakes</a></li>
<li class="chapter" data-level="5.3" data-path="contributor-II.html"><a href="contributor-II.html#sql"><i class="fa fa-check"></i><b>5.3</b> SQL</a></li>
<li class="chapter" data-level="5.4" data-path="contributor-II.html"><a href="contributor-II.html#programming"><i class="fa fa-check"></i><b>5.4</b> Programming</a></li>
<li class="chapter" data-level="5.5" data-path="contributor-II.html"><a href="contributor-II.html#data-preprocessing"><i class="fa fa-check"></i><b>5.5</b> Data Preprocessing</a></li>
<li class="chapter" data-level="5.6" data-path="contributor-II.html"><a href="contributor-II.html#data-visualisation"><i class="fa fa-check"></i><b>5.6</b> Data Visualisation</a></li>
<li class="chapter" data-level="5.7" data-path="contributor-II.html"><a href="contributor-II.html#statistics"><i class="fa fa-check"></i><b>5.7</b> Statistics</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="contributor-III.html"><a href="contributor-III.html"><i class="fa fa-check"></i><b>6</b> Contributor: Part I</a><ul>
<li class="chapter" data-level="6.1" data-path="contributor-III.html"><a href="contributor-III.html#collaboration-git"><i class="fa fa-check"></i><b>6.1</b> Collaboration &amp; Git</a></li>
<li class="chapter" data-level="6.2" data-path="contributor-III.html"><a href="contributor-III.html#learning"><i class="fa fa-check"></i><b>6.2</b> Learning</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="statistician.html"><a href="statistician.html"><i class="fa fa-check"></i><b>7</b> Statistician</a><ul>
<li class="chapter" data-level="7.1" data-path="statistician.html"><a href="statistician.html#pipeline"><i class="fa fa-check"></i><b>7.1</b> Pipeline</a></li>
<li class="chapter" data-level="7.2" data-path="statistician.html"><a href="statistician.html#productive-frameworks"><i class="fa fa-check"></i><b>7.2</b> Productive Frameworks</a></li>
<li class="chapter" data-level="7.3" data-path="statistician.html"><a href="statistician.html#decision-tree"><i class="fa fa-check"></i><b>7.3</b> Decision Tree</a></li>
<li class="chapter" data-level="7.4" data-path="statistician.html"><a href="statistician.html#bagging-boosting-stacking"><i class="fa fa-check"></i><b>7.4</b> Bagging, Boosting &amp; Stacking</a></li>
<li class="chapter" data-level="7.5" data-path="statistician.html"><a href="statistician.html#unsupervised-learning---clustering"><i class="fa fa-check"></i><b>7.5</b> Unsupervised learning - Clustering</a></li>
<li class="chapter" data-level="7.6" data-path="statistician.html"><a href="statistician.html#unsupervised-learning---data-reduction"><i class="fa fa-check"></i><b>7.6</b> Unsupervised learning - Data Reduction</a></li>
<li class="chapter" data-level="7.7" data-path="statistician.html"><a href="statistician.html#feature-selection"><i class="fa fa-check"></i><b>7.7</b> Feature Selection</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="project-responsible.html"><a href="project-responsible.html"><i class="fa fa-check"></i><b>8</b> Project Responsible</a><ul>
<li class="chapter" data-level="8.1" data-path="project-responsible.html"><a href="project-responsible.html#data-science-project-as-product"><i class="fa fa-check"></i><b>8.1</b> Data Science project as product</a></li>
<li class="chapter" data-level="8.2" data-path="project-responsible.html"><a href="project-responsible.html#assembling-a-team"><i class="fa fa-check"></i><b>8.2</b> Assembling a team</a></li>
<li class="chapter" data-level="8.3" data-path="project-responsible.html"><a href="project-responsible.html#statistics-1"><i class="fa fa-check"></i><b>8.3</b> Statistics</a></li>
<li class="chapter" data-level="8.4" data-path="project-responsible.html"><a href="project-responsible.html#data-engineering"><i class="fa fa-check"></i><b>8.4</b> Data Engineering</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="butter-knife.html"><a href="butter-knife.html"><i class="fa fa-check"></i><b>9</b> Butter Knife</a><ul>
<li class="chapter" data-level="9.1" data-path="butter-knife.html"><a href="butter-knife.html#soft-skills-1"><i class="fa fa-check"></i><b>9.1</b> Soft Skills</a></li>
<li class="chapter" data-level="9.2" data-path="butter-knife.html"><a href="butter-knife.html#algorithmic-feature-generation"><i class="fa fa-check"></i><b>9.2</b> Algorithmic feature generation</a></li>
<li class="chapter" data-level="9.3" data-path="butter-knife.html"><a href="butter-knife.html#programming-skills"><i class="fa fa-check"></i><b>9.3</b> Programming skills</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="uncategorized-topics.html"><a href="uncategorized-topics.html"><i class="fa fa-check"></i><b>10</b> Uncategorized topics</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Authentic Data Science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="observer" class="section level1">
<h1><span class="header-section-number">Chapter 3</span> Observer</h1>
<div id="about-this-level" class="section level2">
<h2><span class="header-section-number">3.1</span> About this level</h2>
<p>Welcome to Level 2: Observer. Once you reach this level, you will be able to act as an Observer of a Data Science project. You are <strong>not yet directly able to contribute</strong> to it (such as through coding), but you will be able to <strong>use outputs of it and help with the inputs</strong>. Thus if you are a campaigns manager in the marketing department, you will know what to ask Data Scientists for and how you can use what they create. Also, you will have some basic tools with which you can <strong>evaluate</strong> whether the Data Scientist that your initiative is dependent on did a good job or not. As I mentioned, you will also be able to help out with inputs. Whether you know it or not - Data Science is dependent on people like you, who have the context knowledge. That is why there is the famous saying, “Garbage in, Garbage out”. If you will be able to point a Data Scientist to what he should use and what he should not use, he will be grateful (unless he is stubborn). We will need to develop your skills in three different areas:</p>
<p>Soft understanding of Data Science</p>
<ul>
<li>Be Skeptical About Data</li>
<li>Data Science Project</li>
<li>Your Contribution to Data Science Project</li>
</ul>
<p>Programming</p>
<ul>
<li>Data and Computing</li>
<li>Using Data</li>
</ul>
<p>Statistics &amp; Machine Learning</p>
<ul>
<li>Descriptive Statistics</li>
<li>Machine Learning</li>
<li>Supervised Learning</li>
</ul>
</div>
<div id="be-skeptical-about-data" class="section level2">
<h2><span class="header-section-number">3.2</span> Be Skeptical About Data</h2>
<p><em>Is data really powerful?</em></p>
<p>Being skeptical about the power and bias in your data is the most <strong>crucial</strong> skill, or <strong>mindset</strong> which you will acquire on this level. Even experienced Data Scientists sometimes forget this point. Firstly, let’s think about the power of your data. It might be necessary to ask, whether the data even <em>can</em> answer the questions we intend to ask.</p>
<p>Let’s say that you got a task of optimizing bus transportation in your city, a fairly large city. The optimization should bring a benefit that the number of busses on each route should be adjusted to the demand, making passengers happier, thereafter using the busses more, earning you money and helping the environment. The dataset which you have available are:</p>
<ul>
<li>Every bus route and number of busses operating it.</li>
<li>Every bus stop and a delay that every bus had on that particular stop.</li>
<li>Every ticket bought - at a bus, at a stop or online.</li>
</ul>
<p>Do you think that this dataset will be sufficient to fulfill the task?</p>
<div class="figure"><span id="fig:bus"></span>
<img src="resources/02-observer/bus.jpg" alt="Is our data powerful enough to optimize the bus routes?"  />
<p class="caption">
Figure 3.1: Is our data powerful enough to optimize the bus routes?
</p>
</div>
<p>You do a perfect Data Science project, utilizing the dataset to its maximum. Some of the things you will do based on a dataset:</p>
<ul>
<li>Bus routes, where people buy most tickets on their stops will increase in the number of buses operating them. You are hoping that this way, the busses which might be crowded will be more comfortable for the large number of people using this route.<br />
</li>
<li>Bus routes, where buses tend to be late are rerouted. You found some alternative paths, alternative places for a bus stop and are hoping that this will decrease the delay which buses have, making people more happy.</li>
</ul>
<p>Seems reasonable right? There is a catch and let’s see what might actually happen as a result of your Data Science project.</p>
<ul>
<li>What will most likely happen is that you might optimize for the opposite. You have increased the buses for people who only occasionally travel with a bus, such as pensioners when they go for a walk in the city centre. You have not optimized for heavy users of bus transportation - commuters who daily commute to and from work.</li>
<li>Similarly, your change in routes meets the opposite of success. The reason why the buses are late on these routes is that these are the major paths for people in the city to use.</li>
</ul>
<p>Why have we failed when we did a perfect Data Science and our assumptions about the bus routes seemed to be very reasonable? The answer is that our <strong>data did not have the power to correctly solve the problem</strong>. What we mainly lacked was the online purchases of tickets as well as yearly subscriptions to public transportation services. Both of these ticket purchases are untraceable. As a matter of fact, people who buy yearly subscriptions are the heaviest users of public transportation and we really have no data about their movement. Thus, our dataset simply did not have the required data. One way to solve this would be to change the system in itself. For instance, even if you have a yearly subscription or a ticket bought online, you have to <em>tag</em> it once you enter a bus. It won’t withdraw any money from your account, though your yearly ticket will be invalid, unless tagged.</p>
<p>The message which I wanted to translate with this short example was not how to optimize public transportation, but so that..</p>
<blockquote>
<p>you shall be <strong>skeptical</strong> about the power of your data.</p>
</blockquote>
<p>To demonstrate this in my experience, I was once working with a digital banking application and we intended to create budgets to many customers. These budgets would be helping you save money and have an overview of how much you are spending on various categories such as groceries, going out or vacations. Even though I was trying various methods it was not working out well. The budgets were absolutely unstable and customers every month spent different amounts on things. How is it possible? Of course <strong>my data did not have the power</strong> to answer the question I was given. Even though we consume similar amounts of things every month, we do not necessarily buy the same amount due to simple reasons - we share with someone. Usually customers have families, wifes, husbands, friends, flatmates and they share expenses among each other. To solve the task properly I would need to link together the people who share their expenses and only then I would be able to answer the question.</p>
<p><em>Are some data specifically biased?</em></p>
<p>When it comes to data, there are two areas which I tend to distinguish:</p>
<ul>
<li><strong>Machine-related Data</strong> that relate solely to machinery or natural processes, oftentimes collected through sensors. You are a chemical engineer running trials and observing time for a certain reaction to happen. You could be a mechanical engineer watching whether an error won’t occur in your machinery. Assuming that your <em>sensor</em> is reliable and well setup, your data should be unbiased as both machine and nature (in this sense) are stable in <em>behavior</em>.</li>
<li><strong>Human-related Data</strong> that display human behavior. <em>Self-reported data</em>, such as surveys. Imagine anything from voting polls, through asking whether someone wants to buy our product, up to even reporting an address of residence. <em>Collected data</em>, such as logs from mobile applications which are tracking human activity.</li>
</ul>
<p>To answer our question whether some data are specifically biased, the simple answer is YES. There is a lot of data from my perspective which is just wrong to be used and you as a Embedded Data Scientist should not use. I do now wish to talk now about <em>data quality</em> issues, but about the nature of data, which is connected with how the data came into existence.</p>
<p>There are a lot of datasets which came to existence by <strong>asking people</strong> regarding their state or opinion. Take elections for instance. If you look at US elections in 2016, for a very long time it was seemingly impossible that Trump will win the elections. Yet, he won, even though the data from polls told us otherwise. What happened is that this (poll) dataset was created by asking people, while unfortunately it is in human nature that:</p>
<ul>
<li>people lie with purpose</li>
<li>people are lazy</li>
<li>people cheat</li>
<li>people want to appear different than they are</li>
<li>people do not know themselves</li>
</ul>
<p>I might seem to be negative again, but this is what my past has taught me. Points which I am mentioning above are in our human nature and now it depends upon whether context will push us into one of these biases. I will bring several examples, but for now let’s stick with these. Due to these biases that affect <em>self-reporting</em>, when your Data Science project is working with people,</p>
<blockquote>
<p>you should not rely on data which were created through <em>asking</em> and <em>self-reporting</em>.</p>
</blockquote>
<p>I will be honest, from my perspective all survey data are just wrong and in today’s world, I would simply skip this practice as we have better means of data collection.</p>
<p>Just last week I headed to my bank as a client with the intention of closing my account. I arrived at the branch (which was completely empty due to early hours) and took a place at the advisor. Upon my announcement, the branch advisor said - “You have a different bank?”, to which I replied positively. When my churning papers were printed and ready for signature, I noticed that there is an explicit field stating a reason for churning, where of course was “Client has a different bank”. There was actually a list of reasons why I was churning - unprofessional staff, bad mortgage offer, bad credit card offerings and expensive services. As a client, I did not argue and let that reason be there. As a Data Scientist though, flames of justice were burning inside of me! Imagine the poor Data Scientist who receives a task to analyze data and determine what causes churn. Oh dear…</p>
<p>Do you think that the bank is not aware of an issue with human biases, such as this one? Of course it is; and so cross-checks are present, when a second advisor needs to arrive to confirm the actions of their colleague. Do you think that the second advisor cares more than the first one about the quality of their data? Of course not.</p>
<p>Which of the points above occurred in this situation?</p>
<ul>
<li>I was <strong>lazy</strong> and I <strong>did not know myself</strong>. I could tell the bank clerk that having another bank is not the real reason, but I just didn’t feel like it. Also, I don’t <em>really</em> know why am I leaving this bank. One morning I woke up and I felt like I do not want to be their client anymore.</li>
<li>My branch advisor was I think <strong>cheating</strong>. He was happy that I agreed to the reason that I have a different bank. I could have used one of the reasons that I am unhappy with the service I am receiving at this branch. This would of course cause his colleagues troubles.</li>
</ul>
<p>Thus if you end up as the poor Data Scientist in this case,</p>
<blockquote>
<p>you should seek ways how to <em>overcome</em> the biased self-reported data.</p>
</blockquote>
<p>Let’s assume you work in a bank and your task is to develop a Data Science model which will <strong>automatically be granting loans</strong>. As you are working within the loans department, you very well know that the primary factor for whether your bank will grant a loan is the income of a customer. You also know that there is a field in your database that says <em>“income”</em> to each one of your customers. Problem solved right? You just collect a few more fields and create a model as you were asked. Well, I recommend something different.</p>
<p>If you will ask around you will find out that this <em>“income”</em> the field was created through self-reporting of your customers. When they are setting up their account, the advisor in a branch will ask them what is their income and they report figure X. Trust me when I say that due to one of the reasons listed above, the customer will report a wrong number. Ok, then - you tell yourself that you are smarter than that and decide to observe customer’s incoming salary transactions which you have tagged in your system. You have overcome the problem of self-reported information, right? You deploy your model into production and run your automatic loaning system.</p>
<p>What will happen is that in some time frauds will arise and there will be a lot of customers who took huge loans and do not pay them back. How could this happen? Well, people learned how to cheat your model for their own benefit. Fraudsters are now once a month sending each other transactions which are tagged by your system as salaries and thereafter your <em>“income”</em> the field for this customer is huge. They are then automatically granted significant loans. So, how can we solve this?</p>
<blockquote>
<p>The key is to obtain information which is desired through data which was created by humans, while he was doing something completely natural and at best, unrelated.</p>
</blockquote>
<p>You need to think about an action, or a process of a customer though which he/she unknowingly <strong>displays his/her truthful income</strong>. What about groceries? We all do grocery shopping, thereafter this might be a reliable source of information. What if you look at how much this customer is spending for groceries monthly and relate it to his/hers assumed income. If you have reported 1500 Euro income, how come that you only spend 100 Euro for groceries? I would rather presume that your income is somewhere around 500 Euro. This is of course not a perfect solution, but what I am trying to translate is the <strong>skeptical thinking</strong> about how to solve the problem with bias about human-related data.</p>
</div>
<div id="data-science-project" class="section level2">
<h2><span class="header-section-number">3.3</span> Data Science Project</h2>
<p><em>How does a Data Science project create benefit?</em></p>
<p>Let’s start from the very end, what should a project generate. It should be new information, in various forms, that creates benefit for a person or company that financed this project. Let me emphasize the point of that the project creates <strong>new information, not new data</strong>. This is because data by themselves has no benefit, and thereafter there would be no point in running a project that creates data and not information. This information can be in various forms, so let’s take a look at some examples:</p>
<ul>
<li><p>When I was at university I was tasked with creation of project, which would take <strong>recordings of people walking</strong> and it should create an information of whether people on the recordings are suffering from Parkinson’s disease or not. Having this information creates various benefits, for instance (if working properly), expensive time for doctors is saved. Ultimately, people could self-administer this test at home without the need of visiting the doctor. The information created was the statement “Has Parkinson disease” or “Does not have Parkinson disease” to every recording.</p></li>
<li><p>Once I ran a project which was supposed to <strong>determine a location of newly opened retail stores</strong> in a country. The input for my project was the network of roads and cities in the country with their respective counts of inhabitants. The information which my project was creating was a potential position of retail stores that would be optimized for a distribution of roads and where people live. This information created a clear benefit - competitive advantage for particular retailers.</p></li>
<li><p>Numerous times in the past I was asked to determine customer’s <strong>probability to purchase an item</strong>. My project always took as an input various customer data such as their demographics while it predicted a probability to purchase a particular item (information). This information has a benefit that a business representative can then decide whether he/she will invest into marketing for a particular customer.</p></li>
</ul>
<div class="figure"><span id="fig:parkinson"></span>
<img src="resources/02-observer/parkinson.jpg" alt="My showcasing how Data Science can diagnose Parkinson disease, through recording of gait on four points on the body."  />
<p class="caption">
Figure 3.2: My showcasing how Data Science can diagnose Parkinson disease, through recording of gait on four points on the body.
</p>
</div>
<p>I could go on, but I guess you already have the picture of what is the single requirement of any Data Science project - <strong>creating an information from which we benefit</strong>. The beneficial information can now really vary in forms. It can be anything as you already saw, but I would like to broaden your horizon even more. The output of a Data Science project can be a single diagram, or even a sentence (thereafter it does not have to be predictive modelling or optimization only).</p>
<p><em>What does a Data Science project look like?</em></p>
<p>Essentially, all Data Science is about are <strong>hypothesis</strong>. This is how hypothesis is defined by Oxford dictionary:</p>
<blockquote>
<p>a supposition or proposed explanation made on the basis of limited evidence as a starting point for further investigation.</p>
</blockquote>
<p>You would be surprised by how many Data Scientists are forgetting some parts of this definition so I would like to focus on it. At the beginning of a project you <strong>suppose</strong> something can be done - “We are able to find ideal locations for our retail stores.”. Then you examine whether you already do not have enough evidence which would answer your supposition - “There is no other retailer similar to us in a given country and as we are new to the country we also have no knowledge.” Finally, as we already discussed, there is a clear benefit if our assumption is fulfilled - “Once ideal locations are found, our stores will be easily accessible by customers and this will be profitable”.</p>
<p>Once you work out your hypothesis, your Data Science project can outset. You will seek for available data that you can use to assess your supposition. In later chapters, you will learn about concepts such as <em>Minimum-Viable-Product</em> or <em>experimentation</em> that will help you to set up a simple way as possible to assess your supposition. But, let’s leave it here from now - remember to always set up a project based on your hypothesis.</p>
</div>
<div id="your-contribution" class="section level2">
<h2><span class="header-section-number">3.4</span> Your Contribution</h2>
<p><em>How can I contribute to the Data Science project?</em></p>
<p>I have to make a small assumption here about who you are. You are someone who works in a certain domain - for example banking, paper industry, insurance, car sales, anything. You either have formal education in this domain, or working experience. This means that you have something that no Data Scientist has - specific knowledge of the domain. Thereafter, as we already mentioned, you can contribute to the Data Science project in two ways already on this level:</p>
<blockquote>
<p>As Observer, contributes through inputs and through outputs of Data Science projects, not into the central process.</p>
</blockquote>
<p>As you already know, the basis of every Data Science project are <em>data</em> (input). As you have domain knowledge, you might know about data that Data Scientist is not aware of. I will demonstrate this from one project of mine from the past.</p>
<p>My project was using log data from a mobile application, whereas users had to go through several screens in order to complete the purchase process. I collected all the log data and what it was showing was that a certain group of users was dropping off from the sales process at various points. I was struggling with it and I was unable to explain why this group of users (which had no clear characteristics) was dropping off at various times during the day. I was then approached by a call center representative, which for several years sells the same product over the phone. He did not even have to look at the data and gave me the answer! These were parents of young children! As the sales process takes an hour to get through all the screens, there is a solid probability that if you are a parent of a baby, the baby will start crying and you will of course leave your computer. The data would never reveal me this pattern, the domain knowledge did instantly. You can be the gentleman from the call centre, which moves the project a light year ahead!</p>
<p>Secondly, every data science project should produce an <em>information</em> (output) that will be used to create benefit. This component of the Data Science project is oftentimes underappreciated and you can be the one who fixes it. I will now go back to my projects where I was supposed to predict the probability that a customer purchases a product. I was given this task by our CRM department to optimize email campaigns - so that these are sent only to customers who have decent probability to buy the item. Everything worked well, the Data Science project ran through, the <em>information</em> was created. BUT, the created benefit was close to nothing. As it later turned out, customers are generally overfed with emails and digital channels. I then met with a representative from our branch segment and he said that this <em>information</em> could be of great use for our sellers. The sellers have only very limited time when the customer approaches them and thereafter having the <em>information</em> they will be able to sell more. The data, nor my knowledge of Data Scientist would never reveal this use of the <em>information</em> which I created, the domain knowledge did. You can be this representative, who will multiply the created benefit out of a Data Science project.</p>
</div>
<div id="data-and-computing" class="section level2">
<h2><span class="header-section-number">3.5</span> Data and Computing</h2>
<p><em>How is data represented?</em></p>
<p>If you plan on skipping this chapter, because it seems boring, please don’t. It would come to haunt you in your glorious future of Embedded Data Scientist. Data Science is done using computers, thereafter I think it is crucial to understand how your computer sees data. We often think that computers are smart, while in fact they are quite basic - they understand only two values - 1’s and 0’s. In fact some of the earliest computers were presented data through punch cards.</p>
<div class="figure"><span id="fig:punch-cards"></span>
<img src="resources/02-observer/punch-cards.jpg" alt="Example of how one of the earliest versions of computers from IBM saw data - as punchards with holes (1s) and not-holes (0s). Picture by dansimmons on Twitter"  />
<p class="caption">
Figure 3.3: Example of how one of the earliest versions of computers from IBM saw data - as punchards with holes (1s) and not-holes (0s). Picture by dansimmons on Twitter
</p>
</div>
<p>How is it possible that two values are enough to represent anything to the computer? Through converting numbers into binary form. I do not want to bother you with the details of this method, I just want to tell you that <strong>any number is easily represented in a binary form</strong>.</p>
<div class="figure"><span id="fig:text-to-binary"></span>
<img src="resources/02-observer/text-to_binary.jpg" alt="Example of how texts and numbers can be encoded into binary."  />
<p class="caption">
Figure 3.4: Example of how texts and numbers can be encoded into binary.
</p>
</div>
<p>Now what we often times make mistake with is that we <strong>overestimate powers of computers</strong> and we think that they understand anything - texts, colours, pictures. Well, they don’t. They only really well understand numbers as these can be easily converted into binary form. Thereafter a lot of tasks of Data Scientists revolve around representing data well for the computer. If a Data Science project intends to work with images or texts, one of the most crucial tasks is, how do we convert these to numbers, so that they can be represented well for computers in binary forms?</p>
<p>I was at a conference where a Scandinavian bank was representing their project of revealing fraud transactions by the means of Data Science. Transaction usually looks as something like following:</p>
<div class="figure"><span id="fig:transaction"></span>
<img src="resources/02-observer/transaction.JPG" alt="Example of how we view a transaction."  />
<p class="caption">
Figure 3.5: Example of how we view a transaction.
</p>
</div>
<p>However what a presenter showed was something like following:</p>
<div class="figure"><span id="fig:transaction-representation"></span>
<img src="resources/02-observer/transaction-representation.jpg" alt="Example of how it might be necessary to alter transaction so that our computer views it correctly."  />
<p class="caption">
Figure 3.6: Example of how it might be necessary to alter transaction so that our computer views it correctly.
</p>
</div>
<p>One of the keys of their project is how the transactions were represented to the computer (and algorithm). We will get more into this later. Important message that I would like you to learn now is that;</p>
<blockquote>
<p><strong>data representation</strong> is one of the key components of successful Data Science.</p>
</blockquote>
<p>Usually it will be rather simple to represent data to an algorithm. In the next chapter we are going to learn about data types and in most of the cases this will be sufficient. Though as you will be meeting some more complex projects, such as Natural Language Processing, the topic of data representation will become more prevalent.</p>
<p><em>How does my PC handle data?</em></p>
<p>As soon as you start a Data Science project, you will be facing hardware limitations. Simple reason for this is that hardware costs. Sure, you can purchase a hardware and have no variable costs, but this hardware will be getting outdated or you might incur opportunity costs. Thereafter, every Data Science project will be optimizing for as little hardware requirements as needed to fulfill particular tasks. These requirements will be coming from four crucial components that a computer has and I think it is hence crucial for you to learn about them now.</p>
<p>In order to process data, and run Data Science project, following four components will be needed and this is how I think about them:</p>
<ul>
<li><strong>CPU</strong> (central processing unit). This is a place where all the calculations take place. When you will work with algorithms which are <em>computation heavy</em> and are dependent on the CPU, you will run into limitations.</li>
<li><strong>RAM</strong> (random access memory). This is memory which is instantly accessible to all the programs, thereafter it is super useful to our work when we need to work on some data. When you will work with larger datasets, RAM requirements can become problematic.</li>
<li>Harddisk. This is your “bookshelf” of data. Once you are done working with your data, you store them here until next time you need them. Usually, harddisk space does not pose limitations to your project, as it is fairly cheap.</li>
<li>GPU (graphical processing unit, or graphics card). This is an alternative to your CPU, which is considerably more powerful and will come in handy in late chapters of this book.</li>
</ul>
<div class="figure"><span id="fig:computer-components"></span>
<img src="resources/02-observer/computer-components.jpg" alt="Remember that for a Data Scientist hardware matters - mainly CPU and RAM powers."  />
<p class="caption">
Figure 3.7: Remember that for a Data Scientist hardware matters - mainly CPU and RAM powers.
</p>
</div>
<p><em>What is a csv?</em></p>
<p>Now that we know what data is, we also know what we aim to do with it and how will we manage it with our computer, it is time to get our hands on some data. The simplest representation of a dataset is through so called “csv” or <strong>“comma-separated-values”</strong>. In plain form, these might look something like this.</p>
<div class="figure"><span id="fig:csv-example-1"></span>
<img src="resources/02-observer/csv-example-1.JPG" alt="One customer representation in csv form."  />
<p class="caption">
Figure 3.8: One customer representation in csv form.
</p>
</div>
<p>It is quite ugly right? The reason is that data in this form are <strong>not meant for a human eye</strong>, but for programs to read which can in turn display the data in a nicer way for us. Later on when you will be importing such data, you only need to specify two things so that our program knows how to read it in well:</p>
<ul>
<li>Separator (what separates columns), in our case <code>,</code>.</li>
<li>Whether the first line is a header (names of columns), in our case <code>yes</code>.</li>
</ul>
<p>If you ever worked in Excel, when you are saving a document, you can decide to save it as “.csv”. This is by the way a good practice as the environments you will later on learn to work with can read it easily.</p>
<p><em>What is an observation and a feature?</em></p>
<p>Data Science project will be aimed at certain phenomena which is of our <em>interest</em>. This can be our customer base, weather, how certain machines operate, how our colleagues work - anything. In order to apply Data Science to this phenomena, we will need to <strong>describe it through observations and features</strong>. <em>Observation</em> is some small unit from our phenomena such as a day, one customer, one colleague, one moment of machine’s operation. Secondly, <em>feature</em> is characteristic of an observation, such as temperature in a given day, age of one customer, arrival of our colleague to work or speed of machine’s operation. Here is a small table to summarize it:</p>
<table>
<thead>
<tr class="header">
<th align="right">Phenomena</th>
<th align="right">Observation</th>
<th align="right">Feature</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">weather</td>
<td align="right">day/hour/minute</td>
<td align="right">humidity</td>
</tr>
<tr class="even">
<td align="right">customer base</td>
<td align="right">one customer</td>
<td align="right">age of customer</td>
</tr>
</tbody>
</table>
<p>Throughout your entire career, you will be meeting these two concepts of <em>observation</em> and <em>feature</em>. These will vary in forms, but the way we described it now will always hold. Thereafter we can adjust our csv file and we can represent in it one customer with some of his features. As a standard, <em>features</em> are displayed in <strong>columns</strong>.</p>
<div class="figure"><span id="fig:one-customer"></span>
<img src="resources/02-observer/one-customer.JPG" alt="One customer representation in csv form."  />
<p class="caption">
Figure 3.9: One customer representation in csv form.
</p>
</div>
<p><em>What is a “flat table”?</em></p>
<p>We now learned how to store data about one customer, but we have many customers right? To store data about all of them in reasonable form, we will use a flat table. It is common to store <em>observations</em> in <strong>rows</strong>. Thereafter, we can just add several rows, representing several customers.</p>
<div class="figure"><span id="fig:flat-table"></span>
<img src="resources/02-observer/flat-table.JPG" alt="Multiple customers representation in csv form - flat table."  />
<p class="caption">
Figure 3.10: Multiple customers representation in csv form - flat table.
</p>
</div>
<p><em>What is granularity?</em></p>
<p>Even though we can now store customer’s features nicely, we still haven’t won due to the issue of <em>granularity</em>. Some of the features about a customer will have different <em>granularity level</em> and we are unable to store them in the same table in a nice way. What if we wanted to store cups of coffee per day, per customer. With our current knowledge we could do something like this.</p>
<div class="figure"><span id="fig:bad-flat-table"></span>
<img src="resources/02-observer/bad-flat-table.JPG" alt="It would not make too much sense trying to represent data on different granularities in this way."  />
<p class="caption">
Figure 3.11: It would not make too much sense trying to represent data on different granularities in this way.
</p>
</div>
<p>Ugly right? It would be hard to manipulate such data. We need to solve this by introducing more tables, whereas these are on <strong>different granularity level</strong>. We will call this relational database.</p>
<p><em>What is a relational database?</em></p>
<p>Edgar Frank Codd at IBM in 1970 in his paper “A Relational Model of Data for Large Shared Data Banks”, introduced a concept of how the problem above can be solved in a neat way. Luckily for us Data Scientists, Oracle implemented this idea into a working software solution in 1979 (Ever wondered how that company became so successful? This is it.).</p>
<p>We create two tables, with different granularities separately. The only extra point which we need to specify is how are these linked together - for example customer name.</p>
<div class="figure"><span id="fig:relational-database"></span>
<img src="resources/02-observer/relational-database.JPG" alt="Correct representation of data on different granularities - relational database."  />
<p class="caption">
Figure 3.12: Correct representation of data on different granularities - relational database.
</p>
</div>
<p>When you will be contributing to a Data Science project, keep the data granularity in mind. If the data of different granularities enter the project, it is necessary to harmonize their granularities. This can be done for instance through data aggregation which you will learn on the next level.</p>
</div>
<div id="using-data" class="section level2">
<h2><span class="header-section-number">3.6</span> Using Data</h2>
<p><em>Can we already do Data Science?</em></p>
<p>Now that we constructed ourselves a small relational database with everything that we know about our customer base, are we ready to do Data Science? Yes, so let’s give it a try. We are a coffee seller and we are interested in which age group drinks most of the coffee, so that we can better target our marketing efforts.</p>
<p><strong>calculate the example by hand</strong></p>
<p><em>Do I have to do it in this cumbersome way?</em></p>
<p>Luckily, software can of course help us. Now it is time to turn into learning <em>what</em> software can help is and <em>how</em>. We will need an Integrated-Development-Environment (IDE), engine and maybe a library.</p>
<p><em>What is an IDE, engine and package/library?</em></p>
<p>Even though you are right now at the level of Observer, you might already come in touch with programs or libraries which make Data Science projects. Thereafter, it is important to understand the terminology here. The most obvious are so called IDEs - Integrated Development Environments. These are pretty and easy to work in. Currently, some of the most popular ones among Data Scientists are R-Studio and Jupyter Notebooks. This will be a program which runs on a computer (either a physical one or somewhere on the server), that allows you to utilize some computing <em>engine</em>.</p>
<p>There are two very popular engines, which are actually competing with each other - R and Python. Imagine these as a set of functions which are very robust and people like to use them because they are well developed and once a Data Scientist works with them, he can be sure that his work will run.</p>
<p>Finally there are libraries. The engines as well as IDEs are many times licensed under open-source. This makes a lot of sense, because people have a motivation to contribute to these. How will they contribute though? It would be very tricky to integrate work of thousands of people though single software - may it be R or Python. For that, we have <em>libraries</em>. These are way smaller sets of functions, which usually serve a specific purpose. For example, even though R serves Data Scientists, you might decide to write a specific library which will be for Data Scientists which are trying to predict zombie apocalypse. You will include a set of specific functions in your library and you may decide to publish it so that other people can use it.</p>
<div id="r" class="section level3">
<h3><span class="header-section-number">3.6.1</span> R</h3>
<p>R is an engine (or programming language) in which a lot of Data Scientists today work, because of its simplicity and statistical powers. We are able to solve our task with it with several <em>lines of code</em> while we make use of functions which someone else predefined for us. Here is how a solution looks.</p>
<p><strong>insert R solution to the problem</strong></p>
<p>Let’s talk a little bit about what happens. The function mean comes from a predefined library called base.</p>
<p>It’s a bit ugly though, as we did not use any pretty IDE. We can write the same code in R-Studio IDE. This is how it looks.</p>
<p><strong>insert R-Studio solution</strong></p>
<p>Data Scientists of course like this as you can visually distinguish between various elements. The IDE will have much greater functionalities compared to only working in programming language, but we will get to that later.</p>
</div>
<div id="python" class="section level3">
<h3><span class="header-section-number">3.6.2</span> Python</h3>
<p>you can download it with.</p>
</div>
<div id="knime" class="section level3">
<h3><span class="header-section-number">3.6.3</span> Knime</h3>
<p>Usually when people talk about Data Scientists, they mention two languages (or frameworks) - R and Python. I however believe that in the future a different approach will dominate if we would like to grow the numbers and powers of Embedded Data Scientists. These are frameworks which do not necessarily require coding, but can do very similar things (at a tradeoff of being slightly less flexible). One such framework is Knime.</p>
<p>When thinking about Knime, we can forget our distinction between engine and IDE, here we get both things in one. One important difference to R and Python is that here we are not expected to explicitly write code in order to fulfill our data science task. Let’s give it a try.</p>
<p><strong>insert Knime solution</strong></p>
<p>As you can see we are again doing the same steps, just this time they are represented with visual modules instead of lines of code.</p>
<p><em>Should I use R, Python or Knime?</em></p>
<p>As you are on the level of Observer, you should not choose any. At this point, you should only be able to observe a Data Science project, thereafter when your colleagues say that they work in a certain language (most likely one of these three), you know what they talk about and you can see on a very basic level what they are doing.</p>
</div>
</div>
<div id="descriptive-statistics" class="section level2">
<h2><span class="header-section-number">3.7</span> Descriptive Statistics</h2>
<p>Our toolset is quite limited though so far - we can only use <em>measures of central tendency</em>. It is now time to revisit this idea and expand on it with <strong>distributions, percentiles, visualisations and measures of spread</strong>. I would start by showing you <em>why</em> measures of central tendency are often times not enough, and we need to learn further tools. Consider two populations, each one is several measurements of temperature:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">stable_climate &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">11</span>, <span class="dv">12</span>, <span class="dv">13</span>, <span class="dv">14</span>, <span class="dv">15</span>, <span class="dv">16</span>)
unstable_climate &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">4</span>,<span class="dv">10</span>, <span class="dv">14</span>, <span class="dv">18</span>, <span class="dv">20</span>)</code></pre></div>
<p>When we intuitively look at these two populations, they are very different. The first set of temperatures seem to come from a rather “stable” climate when temperatures range between 11-16 degrees. The second set of temperatures seem to be coming from a way more “unstable” climate. On the first day, we seemed to have only 4 degrees and on last day even 20 degrees! Let’s see what happens if we deploy our learned <em>measures of central tendency</em> on these two populations.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mean</span>(stable_climate)</code></pre></div>
<pre><code>## [1] 13.5</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mean</span>(unstable_climate)</code></pre></div>
<pre><code>## [1] 13.2</code></pre>
<p>Based on mean, our most advanced <em>measure of central tendency</em> they appear almost non-different, which is very contradictive to our intuition! The reason is that measures of central tendency will not grasp how are data spreaded, for that, we will need to examine how are observations distributed and spreaded, which is a topic of this chapter.</p>
<div id="range" class="section level3">
<h3><span class="header-section-number">3.7.1</span> Range</h3>
<p>Simplest way how we can look at how is our population distributed, is by looking at its range.</p>
</div>
<div id="distributions" class="section level3">
<h3><span class="header-section-number">3.7.2</span> Distributions</h3>
<p><em>A picture is worth a thousand words</em>, is an old proverb which is true also for us. Within Data Science, this topic is called Data Visualisation and is very broad. We only tip our toes into its waters now by learning how can we <strong>visualise a distribution</strong>. Why would we even want to visualise a distribution? Let’s revisit an example from a previous chapter, where we had salaries distributed such as this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">salaries_country &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">350</span>, <span class="dv">400</span>, <span class="dv">450</span>, <span class="dv">470</span>, <span class="dv">500</span>, <span class="dv">520</span>, <span class="dv">1200</span>, <span class="dv">1270</span>, <span class="dv">1300</span>, <span class="dv">1460</span>, <span class="dv">1500</span>)</code></pre></div>
<p>In this case, it was easy for us to intuitively grasp an idea of what is going on in the population. What is our population looked though like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(large_salaries_population, <span class="dv">100</span>)</code></pre></div>
<pre><code>##   [1] 576 551 904 576 588 623 564 480 639 609 478 595 648 579 676 647 628 729
##  [19] 698 680 635 607 567 673 646 642 595 591 451 559 389 630 758 639 768 502
##  [37] 630 611 814 581 644 653 571 656 599 652 503 633 506 456 604 666 625 486
##  [55] 757 523 716 547 712 693 608 660 518 641 637 585 539 632 638 610 613 533
##  [73] 476 588 724 610 695 582 573 546 593 634 574 502 516 462 633 659 480 590
##  [91] 478 576 649 552 564 580 594 622 557 486</code></pre>
<p>It gets messy right? We can try to order the numbers, but still <strong>our intuitive thinking is failing</strong> when population gets larger. That is why we turn into <strong>distributions plot</strong>. It is one of the simplest plot within Data Visualisation techniques:</p>
<ul>
<li>It has two axis: x-axis (horizontal) and y-axis (vertical)</li>
<li>X-axis displays our values or units of measurement (in our case salaries in Euro). This axis is splitted into small <strong>bins</strong>, each bin holds a range of our values - for example range of 50 Euro, ranging from 900 Euro to 950 Euro.</li>
<li>Y-axis displays <em>count</em> of observations which fall into given bin. If our bin holds a salary range of 900-950 Euro, several observations may fall into it (906, 934, 949). The displayed value on y-axis will then be 3, as 3 observations fell into a bin.</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">large_salaries_population_df &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">salaries =</span> large_salaries_population)
<span class="kw">ggplot</span>(large_salaries_population_df, <span class="kw">aes</span>(<span class="dt">x =</span> salaries)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">100</span>)</code></pre></div>
<p><img src="intuitive-ds-book_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>Our intution works again doesn’t it? By looking at the plot of salary distribution, we can imagine what is happening in the population. We can clearly see part of population whose salaries are distributed around 600 Euro, whereas this is majority of population. Second hump occurs around 1000 Euro, where is a wealthier group of people distributed. If we now worked for tax office and our task would be to determine a boundary for different tax levels, based on this distribution plot, we would be able to complete the task - we would probably put this cut somewhere around 800 Euro to clearly separate these two populations.</p>
</div>
<div id="quantiles-percentiles" class="section level3">
<h3><span class="header-section-number">3.7.3</span> Quantiles &amp; Percentiles</h3>
<p>We have in the last chapter learned about mode, median and mean. Out of these, median and mean will be very useful for you when you will be thinking essentally about any population. We expand our knowledge now on <em>median</em> with a knowledge that this is also so called <strong>2nd quantile</strong> and as well <strong>50th percentile</strong>.</p>
<p>Do you remember how we said that that median can be obtained by ordering the population from smallest to largest and taking the middle observation, which represents then a median. If we ordered 5 people by height, the person standing right in the middle (3rd person) would represent median height. How useful is this knowledge for us? We are able to <strong>compare</strong> the rest of the population to this median height. We know that everyone standing to the right of this person is taller, and everyone to the left has lower height.</p>
<div class="figure"><span id="fig:boxplot-1"></span>
<img src="resources/02-observer/boxplot-1.jpg" alt="Median represents observation in &quot;the middle&quot;."  />
<p class="caption">
Figure 3.13: Median represents observation in “the middle”.
</p>
</div>
<p>Wouldn’t it be useful if we could be more detailed and not only compare the population to the exact middle? <strong>Quantiles</strong> are a way for us to do so. Similarly how median did split population into two parts, with equal number of observations in each; quantiles will split population into <strong>four parts</strong> each with approximately same number of observations.</p>
<div class="figure"><span id="fig:boxplot-2"></span>
<img src="resources/02-observer/boxplot-2.jpg" alt="Quantiles split the population into 4 parts, each having approximately 25% of observations."  />
<p class="caption">
Figure 3.14: Quantiles split the population into 4 parts, each having approximately 25% of observations.
</p>
</div>
<p>Next tool which Data Scientist believe is very useful, is to look how far are 1st and 3rd quantile from each other, this is called “Interquantile Range (IQR)”. In other words, IQR tells us, in what <em>range</em> the middle 50% of the population lies.</p>
<div class="figure"><span id="fig:boxplot-3"></span>
<img src="resources/02-observer/boxplot-3.jpg" alt="Interquantile range shows us a range of middle 50% of the population."  />
<p class="caption">
Figure 3.15: Interquantile range shows us a range of middle 50% of the population.
</p>
</div>
<div class="figure"><span id="fig:boxplot-4"></span>
<img src="resources/02-observer/boxplot-4.jpg" alt="Multiplying of IQR with either 1.5 or 3 will allow us to find observations which lie too far from the rest of the population."  />
<p class="caption">
Figure 3.16: Multiplying of IQR with either 1.5 or 3 will allow us to find observations which lie too far from the rest of the population.
</p>
</div>
<p>Finally, our picture starts to be a little cluttered and hard to look at. That is why Statisticians came with a very simple method of how all the previously discussed measures (median, quantiles, IQR…) can be put into one plot, called <strong>Box plot</strong> (or Boxplot). This powerful visualisation tool will allow us to instantly visualise the population.</p>
<div class="figure"><span id="fig:boxplot-5"></span>
<img src="resources/02-observer/boxplot-5.jpg" alt="Boxplot is a simple and powerful tool for examining a population."  />
<p class="caption">
Figure 3.17: Boxplot is a simple and powerful tool for examining a population.
</p>
</div>
<p>Where in the population you lie, to compare yourself.</p>
</div>
<div id="extreme-values-and-outliers" class="section level3">
<h3><span class="header-section-number">3.7.4</span> Extreme Values and Outliers</h3>
<p>You might have noticed in the boxplot above, that a few points are <em>outside</em> of the whiskers, which are representing a distance of 1.5 IQR from respective quantile. As we already mentioned, these whiskers usually have length of either 1.5 or 3 times of IQR and there is a sound statistical reason for that. As it seems, points which lie outside, may be regarded as <strong>outliers</strong>. Outlier is a point which is so far from the average of the population (the middle 50% of values), that it should be looked at with care. Usually <em>outliers</em> have special meaning and we should examine them. Maybe they tell us that few of our observations are special, which can already be a valuable information.</p>
<p>There is also a possibility that an outlier is an <strong>extreme value</strong> which is usually unfortunate. As compared to outliers, which are occuring naturally, <em>extreme values</em> occur for unnatural reason, such as error while we were collecting the data.</p>
<p>It is important to recognise that both outliers and extreme values can have significant impact on our analysis of population.</p>
<p>In the following example we will look at mean and median of a population. Median is not necessarily influenced by the outliers, while mean can be a lot.</p>
</div>
<div id="percentages" class="section level3">
<h3><span class="header-section-number">3.7.5</span> Percentages</h3>
<ul>
<li>the danger of working with them (CRM campaigns doubling conversion rate)</li>
<li>they are relative to some amount (which can be small)</li>
</ul>
</div>
<div id="comparing-distributions" class="section level3">
<h3><span class="header-section-number">3.7.6</span> Comparing Distributions</h3>
<p>Learn about comparing populations with distributions.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df.example &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">model =</span> <span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;a&quot;</span>, <span class="st">&quot;b&quot;</span>), <span class="dt">length.out =</span> <span class="dv">500</span>), 
                      <span class="dt">type =</span> <span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;t1&quot;</span>, <span class="st">&quot;t2&quot;</span>, <span class="st">&quot;t2&quot;</span>, <span class="st">&quot;t1&quot;</span>), 
                      <span class="dt">length.outh =</span> <span class="dv">250</span>), <span class="dt">value =</span> <span class="kw">rnorm</span>(<span class="dv">1000</span>))

d2 &lt;-<span class="st"> </span>df.example <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(model, type) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">lower =</span> <span class="kw">quantile</span>(value, <span class="dt">probs =</span> .<span class="dv">025</span>),
            <span class="dt">upper =</span> <span class="kw">quantile</span>(value, <span class="dt">probs =</span> .<span class="dv">975</span>))

<span class="kw">ggplot</span>(df.example, <span class="kw">aes</span>(<span class="dt">x =</span> value)) <span class="op">+</span>
<span class="st">  </span><span class="kw">facet_grid</span>(type <span class="op">~</span><span class="st"> </span>model) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">fill =</span> model, <span class="dt">colour =</span> model)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">data =</span> d2, <span class="kw">aes</span>(<span class="dt">xintercept =</span> lower)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">data =</span> d2, <span class="kw">aes</span>(<span class="dt">xintercept =</span> upper))</code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="intuitive-ds-book_files/figure-html/comparing_distributions-1.png" width="672" /></p>
</div>
</div>
<div id="predicting-the-future" class="section level2">
<h2><span class="header-section-number">3.8</span> Predicting The Future?</h2>
<p>We are not focusing too much on inferential statistics, as for you as Embedded Data Scientist, you will be more often tasked with predicting of future values.</p>
<p>Describing a population, in order to draw some actionable insights is a first step toward data-driven future and decision making. We were thanks to it able to create a lot of value - find ideal weight of new bread to be launched, sligthly optimize taxing system and help design a sunscreen product for optimal temperature. Often times though, this will not be enough and we will want to know, <strong>what will happen in the future</strong>. In essence, we already did it with our temperature example didn’t we? The product which should be optimized for summer temperatures will <em>be used in the future</em>, which means that we already did dare predict the future.</p>
<p>Our capabilities of predicting a future are limited by a lot of factors, which you will slowly learn about throughout the course of this book, though there are two which I would like to touch upon now.</p>
<p>Your prediction is limited by the scope of your past data…</p>
<p>Your prediction is limited by the number of observations…</p>
<p>Do not overestimate your capabilities. From now on, there will be a lot regarding machine learning and you might feel like these methods are really powerful for <em>future prediction</em>, but please always keep in mind our temperature prediction with median - in essence that was a similar model and what machine learning does is very similar to that (statistical models).</p>
<p>Before we start with machine learning, keep in mind that is is always a good practice to build a <strong>baseline model</strong> which should be without the use of these techniques and only then turn to statistical methods, and see whether the use of these even makes sense.</p>
<p>Predicting without Machine Learning - importance of non-ML baseline</p>
</div>
<div id="basics-of-machine-learning" class="section level2">
<h2><span class="header-section-number">3.9</span> Basics of Machine Learning</h2>
<p><em>What is Machine Learning?</em></p>
<p>Machine Learning is a crucial part of Data Science. Oftentimes when I see courses or training materials, this area is postponed until the student learns a lot of basics, such as data preprocessing. Only then, it is believed, you should be exposed to Machine Learning. I believe the opposite - <strong>you should meet it already now</strong> (as an Observer), due to two reasons. Firstly, as already mentioned, Machine Learning is something like a hearth of Data Science. Secondly, it will keep your motivation higher - you need to know some cool things that you will be able to do once you finish this book.</p>
<p>To explain to you properly what Machine Learning is, I need to go into the history of computing. Why did computers arise? They arose to simplify or automate tasks done by humans. One such task was to summarize consensus data (the survey done every 10 years which observes a population of a certain country). The problem in the 1880s was that it took over 8 years to summarize and process the data from a consensus, thereafter making it quite worthless due to the length of the process. One of the clerks, Herman Hollerith proposed a solution through a counting machine that successfully sped up the process.</p>
<div class="figure"><span id="fig:hollerith-machine"></span>
<img src="resources/02-observer/hollerith-machine.jpg" alt="Data processing as a use of computers. Picture by IBM History. See at: https://www.ibm.com/ibm/history/ibm100/us/en/icons/tabulator/"  />
<p class="caption">
Figure 3.18: Data processing as a use of computers. Picture by IBM History. See at: <a href="https://www.ibm.com/ibm/history/ibm100/us/en/icons/tabulator/" class="uri">https://www.ibm.com/ibm/history/ibm100/us/en/icons/tabulator/</a>
</p>
</div>
<p>This was a primary solution for over half a century until commercial electronic computers arrived. Having computers with certain rules which were doing what otherwise humans could do, was really helping humanity. This automation was done by telling computers explicitly what to do through <em>rules</em>. Rules have problems though - they have hard and strict boundaries. If you want to design a great rule based system, you need to be really careful so that you encode all the <em>patterns</em> which are in the data. With the arrival of commercial electronic computers the rule based systems were becoming more and more complex. Firstly, it is very hard to encode all the matters into our model. Secondly, our population and data change over time. Due to that, even if you manage to encode all of the rules, very quickly will these become outdated simply due to the changing nature of our world.</p>
<p>The story of Machine Learning continues at IBM, as here in <strong>1952 Arthur Samuel</strong> came up with the first phrase of Machine Learning. He was interested in designing a computer program to play checkers, while the electrical computer had only a very limited memory available. He was thereafter motivated to write <em>functions</em> which will analyse the game on the go and decide on the next move. You see, this machine no longer had explicit instructions on how to work. If you open the Wikipedia page about Machine Learning, most likely it will be defined through the definition of Arthur Samuel from 1959:</p>
<blockquote>
<p>Machine learning (ML) is the scientific study of algorithms and statistical models that computer systems use to perform a specific task without using explicit instructions, relying on patterns and inference instead. It is seen as a subset of artificial intelligence.</p>
</blockquote>
<div class="figure"><span id="fig:arthur-samuel"></span>
<img src="resources/02-observer/arthur-samuel.jpg" alt="Arthur Samuel is one of the key persons in the history and evolution of Machine Learning. Picture by IBM History. See at: https://www.ibm.com/ibm/history/ibm100/us/en/icons/ibm700series/impacts/"  />
<p class="caption">
Figure 3.19: Arthur Samuel is one of the key persons in the history and evolution of Machine Learning. Picture by IBM History. See at: <a href="https://www.ibm.com/ibm/history/ibm100/us/en/icons/ibm700series/impacts/" class="uri">https://www.ibm.com/ibm/history/ibm100/us/en/icons/ibm700series/impacts/</a>
</p>
</div>
<p>Here we see the difference - instead of explicit instructions, we are going to seek for patterns and inference in our data. By doing so, we will not have to maintain the model manually anymore, like we had to with rules creation. Also, these patterns will have <em>soft</em> boundaries and conditions will not need to be met exactly, but a case needs to come close.</p>
<p>Are we already at the definition of Machine Learning how we know it today? Not quite. You see that even though we are able to let the program decide through identified patterns, instead of explicit instructions, we are not <em>generalized</em> yet. The computer of Arthur Samuel was designed to be good at specific task and we cannot take it and generalize it to playing cards for example, or optimize bus transportation. The next leap forward came from Frank Rosenblatt in 1957 who developed the idea of <strong>perceptron</strong>. Even though it took many years after Rosenblatt introduced the concept, the idea which he proposed was crucial. The Perceptron is a <em>function</em> which could be used for many tasks and not only for one specific.</p>
<div class="figure"><span id="fig:perceptron"></span>
<img src="resources/02-observer/perceptron.png" alt="The Perceptron was the first version of the Machine Learning model as we know it today. It could theoretically be applied to any task at hand." width="827" />
<p class="caption">
Figure 3.20: The Perceptron was the first version of the Machine Learning model as we know it today. It could theoretically be applied to any task at hand.
</p>
</div>
<p>Let’s say that you are running a canteen where a few hundred people arrive every day for lunch. You are supposed to optimize which meals are being served, and also how many portions will be cooked. This should yield a benefit of lowering waste created in your canteen. How will you go about it?</p>
<p>Your Option 1 is <strong>creation of certain rules</strong>. You look into your past and notice that your canteen never sold more than 400 meals in a day. On the other hand, you never sold less than 100 meals. This will be your first rule, to always cook between 100 and 400 meals. Whenever you serve a national dish - Wiener Schnitzel, you are always over 300 servings, people love it. However, if you serve Wiener Schnitzel 2 times in a week, the second time only very few people come, even though people love the meal, they want it only once a week. There is your second rule. If you serve rice as a side dish, some 30 people less always come as compared to potatoes, people tend to like rice less. There is your third rule. Now you can be working through a rule creation for a very long time and construct a list of explicit rules according to which you will operate the canteen.</p>
<p>Your Option 2 is <strong>use of Machine Learning</strong>. You will collect as much data about the past consumption in your canteen. Often times people make a mistake of thinking that I only <em>throw</em> data into Machine Learning algorithms (such as The Perceptron) and it will save you a lot of time. No, you still need to invest your time, but into <em>preparing the data</em> for the algorithm, instead of creating the rules yourself. Thus you will not only collect the meals, their consumption, but also things like public holidays, allergens in the meals. All of this will be nicely prepared, fitted into the Machine Learning model, which will discover various patterns. Now whenever you will be planning to cook a meal, you will push it into your model, and it will <em>predict</em> what will be the consumption.</p>
<p><em>How do I use data for Machine Learning?</em></p>
<p>The definition from Arthur Samuel from 1959 has a second part which might anwer just this question:</p>
<blockquote>
<p>Machine learning algorithms build a mathematical model based on sample data, known as “training data”, in order to make predictions or decisions without being explicitly programmed to perform the task.</p>
</blockquote>
<p>We are going to show our <em>Machine Learning model</em> a set of our data, which we will call <strong>training data</strong>. The underlying statistical and/or mathematical model will seek for the patterns. Once those are found, the model will be <em>trained</em> to recognise learned patterns. Once the model is trained, we can present some new data that the model has never seen and ask the model to make a <strong>prediction</strong> about this new data. Imagine a child which has never seen a monkey (<em>untrained model</em>). We will now walk the child through several zoos and show him various monkeys (<em>training data</em>). The child has learned to recognise and identify a monkey whenever it sees one (<em>trained model</em>).</p>
<p>How is our <em>trained model</em> beneficial to us? We can show it <strong>unseen data</strong>, which we usually call <strong>unlabelled data</strong> and ask the model to make a prediction for these. This is the case when we would ask the child what it sees and it should identify a monkey.</p>
<p>If we go back to our example with canteen:</p>
<ul>
<li>Training data is all our data from <em>past</em> which we can collect. We <em>know</em> how much of each meal was consumed.</li>
<li>Unlabelled data for which we would like to obtain prediction is our plan of what meal to cook <em>tomorrow</em>. We <em>want to know</em> how much of our planned meal tomorrow will be consumed.</li>
</ul>
<p><em>Do I need Machine Learning?</em></p>
<p>Now that we know what Machine Learning is, I would like to stop for a second and think about whether we need it at all. These are questions that even experienced Data Scientists often times forget to ask and they end up with what I call <em>“overkill”</em>. If you are considering application of Machine Learning, the first thing you should ask yourself is <strong>whether simpler methods cannot answer your issue</strong>. The simple reason for this consideration is that Machine Learning could get expensive (we will get to the details in later chapters of the book).</p>
<p>I will recall one Kaggle competition to give you an example (we will get to those later as well). The competition was regarding a mobile game for kids. This game includes various activities such as videos, games and assessments (tests). The task for a Data Scientist was to predict how many attempts it will take the kid to pass an assessment. Our <em>training data</em> were all the assessments played in the past by hundreds of kids. There was also <em>unlabelled data</em>, the most recent assessment of kids.</p>
<p>There were many people who instantly jumped to Machine Learning and spent hours trying to apply it to the problem at hand, while thinking that their solution is pretty decent. All of a sudden a solution came which contained only 10 lines of code. All that the author of this submission did was that he looked at the average number of attempts that kids needed to solve a particular assessment. As there were only four unique assessments, he really only quickly calculated a mean out of <em>training data</em>. His calculation was hence only four numbers and he assigned to unlabelled data the one, which respective assessment a kid was about to solve.</p>
<p>By making such simple predictions, the author beat everyone’s Machine Learning solution until that day. He set a new baseline of what people need to beat in order to <strong>justify the use of Machine Learning</strong>. Keep this in mind and in the future always consider whether a simpler solution might not answer your task. IF this Kaggle competition was real world, maybe this solution would be sufficient enough, and by being extremely cheap, we would satisfy the requirement.</p>
</div>
<div id="supervised-learning" class="section level2">
<h2><span class="header-section-number">3.10</span> Supervised Learning</h2>
<p><em>What is supervised learning?</em></p>
<p><em>Need rewrite: In Statistics, regression, if you are attempting to build a model based on empirical data, to predict some response variable based on one or more explanatory variables or more variables–then you are doing regression analysis. It doesn’t matter whether the output is a continuous variable or a class label (e.g., logistic regression). So for instance, least-squares regression refers to a model that returns a continuous value; logistic regression on the other hand, returns a probability estimate which is then discretized to a class labels.</em></p>
<p>Machine Learning has several subfields to it, on this level (Observer) you are only going to learn the most applicable one - Supervised Learning. Supervised learning deals with issues where we have so called <strong>target feature</strong>. Do you remember how we discussed <em>observation</em> and its <em>characteristics</em>? Target feature is going to be one <em>characteristic</em>, which is for certain reasons of our interest. We are interested in <em>training</em> the Machine Learning model to be accurately <em>predicting</em> our target feature. The rest of the <em>characteristics</em> will be called <strong>independent features</strong> and will be used to predict <em>target feature</em>.</p>
<p>The naming conventions are quite important to learn. The name <em>independent features</em> is coming from our assumption that these features are independent from each other and from the environment. That is why we can use them to predict <em>target feature</em>. This can be also called <em>dependent feature</em> as we are making an assumption that this feature is <em>dependent</em> on independent features.</p>
<div class="figure"><span id="fig:machine-learning-areas-1"></span>
<img src="resources/02-observer/machine-learning-areas-1.png" alt="The first of Machine Learning that we will focus on is Supervised Learning." width="360" />
<p class="caption">
Figure 3.21: The first of Machine Learning that we will focus on is Supervised Learning.
</p>
</div>
<p>If we go back to our example regarding canteen meal consumption, this is an example of Supervised Learning. Let’s look at what we have as <strong>training data</strong>:</p>
<p>Independent features:</p>
<ul>
<li>allergens in a meal</li>
<li>day of week</li>
<li>calories in a meal</li>
<li>structure of the meal</li>
</ul>
<p>Target feature:</p>
<ul>
<li>number of meals consumed</li>
</ul>
<p>We can proceed to the training of Supervised Machine Learning models. As we said, we will pick one general algorithm available to us and feed it with our training data. This way, the model will become <strong>trained</strong> and we are hoping that it can make correct predictions for the future. As a canteen manager, I will plan the meal for the next day in the afternoon of the previous day. I will decide that I want to cook a certain meal. This is what I will know about my meal tomorrow:</p>
<p>Independent features:</p>
<ul>
<li>allergens in a meal</li>
<li>day of week</li>
<li>calories in a meal</li>
<li>structure of the meal</li>
</ul>
<p>Notice, that I am <strong>missing target feature</strong>, as this is my <strong>unlabelled data</strong>. I will now reach to my trained Machine Learning model to <strong>make a prediction of target feature</strong>. The model will return for instance that it predicts that 255 people will come to consume the meal which I am planning to serve.</p>
<p><em>Is target feature always straightforward?</em></p>
<p>As you see, target feature is a crucial component in Supervised Learning. Is it always easy and straightforward to find a correct target feature? No. Oftentimes, finding and clarifying a target feature is going to be among the hardest parts of Supervised Learning. If you remember how I was in the previous chapter claiming that any lecturer or training who promises to prepare you with exercises for the real world - target feature definition is actually one of the reasons.</p>
<blockquote>
<p>There will be numerous projects where you will really need to think hard to create a target feature, which will allow you to construct a Supervised model.</p>
</blockquote>
<p>I was once working on a project within environmental studies. The project was focused on how human activity influences deer populations in certain Swedish forest. Even though the forest was large enough for a population of deers, the worry was that building small roads, electrical lines and similar man-made objects will influence the deers negatively.</p>
<div class="figure"><span id="fig:deer"></span>
<img src="resources/02-observer/deer.jpg" alt="Can human activity negatively influence deers? Photo by steve-130217 from Pexels."  />
<p class="caption">
Figure 3.22: Can human activity negatively influence deers? Photo by steve-130217 from Pexels.
</p>
</div>
<p>Data were collected over the span of several years. Researchers did a specific method of pellet observation to determine in which areas of the forest the deer spend their time. During these years, few new roads were built and one electrical line. My task was to build a Supervised model which could be used in other Swedish forests, when there will be a plan to build roads or electrical lines. By having such a model, environmentalists could stop constructions which would negatively influence the deer population. The question which now bothered me was <strong>what is the right target feature which I should use</strong>?</p>
<p>One option would be to only look at whether the deer is or is not in this area of the forest. This is not quite right though. Deers move a lot around the forest and most likely, within one year they will visit at least once most of the areas in the forest. My model could then be too optimistic, saying that nothing influences deers and they happily run around the forest.</p>
<p>Another option would be to predict how many times the deer pellet was found in a particular area.</p>
<p>Now I still needed to incorporate in my model, the <em>change</em> itself. The data were being collected over a span of time and I needed to see how my target feature changes over time. As you see the definition of target variable for Supervised Learning might be a really tedious process. With this chapter, I do not intend to give you guidelines on how to construct target variables correctly but to give you a mindset to…</p>
<blockquote>
<p>always consider and question whether your target feature is correct and appropriate</p>
</blockquote>
<p>We will get more into details and nuances regarding target features on the next level of Contributor.</p>
</div>
<div id="pitfalls-of-machine-learning" class="section level2">
<h2><span class="header-section-number">3.11</span> Pitfalls of Machine Learning</h2>
<p><em>What is underfitting and overfitting?</em></p>
<p>Machine Learning, and supervised learning are fields which have certain pitfalls. Now that we know how Machine Learning works, it is time that we learn about these. I will start the explanation with a quote from George Box, famous statistician:</p>
<blockquote>
<p>All models are wrong, but some are useful.</p>
</blockquote>
<p>As there is a lot of discussion in literature about this famous quote, I guess we can make our own interpretation. When it comes to the second part of this definition that <em>some models are useful</em>, we have already discussed this. You can build a Data Science model for essentially anything, the key is to build a model which will <em>be useful</em> and create benefit. What is more relevant for us now, is the first part of the quote - <em>all models are wrong</em>.</p>
<blockquote>
<p>However well we fit a model, it will never be perfect at predicting unseen data.</p>
</blockquote>
<p>We have a new term here - <strong>unseen data</strong>. This is simply data that was not used during training of our model. That is why our trained Machine Learning model cannot be adjusted for this dataset. And, as it usually is, unseen data is always at least slightly different to the original training data. Whichever process in the real world that you will be working with, the unseen data will possess some new nuances that your model cannot foresee. Let’s look at the following picture.</p>
<div class="figure"><span id="fig:raw-data"></span>
<img src="resources/02-observer/raw-data.jpg" alt="Training data will always be different from unseen, unlabelled data for which our model should predict."  />
<p class="caption">
Figure 3.23: Training data will always be different from unseen, unlabelled data for which our model should predict.
</p>
</div>
<p>Let’s relate to some examples that we already went through and observe whether unseen data will be different to training data:</p>
<ul>
<li>My model which was supposed to predict whether a person has Parkinson disease, based on characteristics of gait, has this issue. When a new person is observed, this person will have different height and weight. The walking style and clothing will also be different - no two persons walk or dress exactly the same.</li>
<li>Our model of bus transportation optimization, will certainly have this issue. If we would fit a Machine Learning model, every day in a large city transportation system is different. Some buses will have mechanical issues and there will also be new traffic incidents on the road.</li>
</ul>
<p>You might be now slightly confused between the two terms - <strong>unseen</strong> data and <strong>unlabelled</strong> data, which we introduced earlier. Unlabelled data is part of unseen data. As this data does not have labels, we certainly could not use it for training of our model. I will clarify this further in the next section, though for upcoming lines I would like to ask you to clear your mind and think only about two terms - <strong>training</strong> data and <strong>unseen</strong> data.</p>
<p>In the picture above, which compares training and unseen data, we can see the exact case. The data on the left, which will be used for training of the model are different from the unseen data. We are running into a danger of <strong>overfitting of the model</strong> if we don’t take this into account.</p>
<blockquote>
<p>Overfitted model is one, which is too adjusted to describe training data well, at the cost of losing predictive power on unseen data.</p>
</blockquote>
<p>Let’s fit such a model so that we see what is happening. We fit a model which describes our training data perfectly. We then observe how good it is at describing unseen data on the right.</p>
<div class="figure"><span id="fig:overfit"></span>
<img src="resources/02-observer/overfit.jpg" alt="Overfitted model is great at describing our training data, but poor when it comes to unseen data."  />
<p class="caption">
Figure 3.24: Overfitted model is great at describing our training data, but poor when it comes to unseen data.
</p>
</div>
<p>It is not great, right? The reason why is what I described earlier, your training and unseen data are <strong>always different</strong>. The solution to this is to aim for our model to <strong>generalize better</strong>.</p>
<blockquote>
<p>Model generalizes well, if it can retain predictive power not only on training data, but also on unseen data.</p>
</blockquote>
<p>We can try to fit such model, we will draw the line in a bit more <em>ignorant</em> way towards our training data.</p>
<div class="figure"><span id="fig:balanced-fit"></span>
<img src="resources/02-observer/balanced-fit.jpg" alt="Balanced model describes our training data well and also generalizes well for unseen data."  />
<p class="caption">
Figure 3.25: Balanced model describes our training data well and also generalizes well for unseen data.
</p>
</div>
<p>This looks more reasonable right? We call this a <em>balanced fit</em> as this model generalizes well. Being a little <em>ignorant</em> toward our training data allowed us to fit a model which has better predictive power on unseen data. We have to be careful to not be <em>too ignorant</em> toward the training data. If we were, what would happen is that we would fit <strong>underfitted model</strong>. Such a model as bad at describing both - training and unseen data.</p>
<div class="figure"><span id="fig:underfit"></span>
<img src="resources/02-observer/underfit.jpg" alt="Underfitted model is bad at describing both training as well as unseen data."  />
<p class="caption">
Figure 3.26: Underfitted model is bad at describing both training as well as unseen data.
</p>
</div>
<p>The concept through which we just went is in literature often times called <em>Bias-variance tradeoff</em>. I do not want to teach you the idea through this terminology as I find it a little confusing and tricky to remember. Keep in mind the terms of <strong>overfitting, underfitting and balanced fit</strong>.</p>
<p><em>What is a validation set?</em></p>
<p>We now know that we should avoid overfitting or underfitting of our model. How do we prevent it though? What we have in our toolkit now is only two sets of data - training data and unlabelled data. In the previous section we have used the term unseen data. We saw that in order to evaluate whether our model achieves <em>balanced fit</em> we need to have two sets, for which we know the label. That is why we need to introduce a new concept called <strong>validation data</strong> which will clear all of these terms in your mind. Let’s look at the following picture.</p>
<div class="figure"><span id="fig:all-datasets"></span>
<img src="resources/02-observer/all-datasets.jpg" alt="An overview in terminology and use of datasets for training and validation of Machine Learning model."  />
<p class="caption">
Figure 3.27: An overview in terminology and use of datasets for training and validation of Machine Learning model.
</p>
</div>
<p>We start our process of thinking on the top - some data are <strong>labelled</strong> and some are <strong>unlabelled</strong>. In case of our canteen, labelled data are our past data of meal consumption. Unlabelled data is tomorrow - we only know independent features, such as what we are going to cook, we do not know how many people will consume it.</p>
<p>Now we focus on labelled data, which we split into two parts - <strong>training</strong> data and <strong>validation</strong> data. A common practice is to use 20% of labelled data for validation data. In case of our canteen, we have data from the past 5 months labelled. We know how much of each meal has been consumed every day in the past 5 months. We cut away for instance the most recent month for validation data, so we will be left with the first four months as training data.</p>
<p>Finally, we can focus on <strong>unseen</strong> data. We have learned in the previous section that some data will be unseen to the model. This will be two sets - unlabelled and validation data. Unlabelled data are unseen to our model, simply because they do not have labels and we cannot use them for training of our model. Validation data will be unseen to our model, so that we will be able to address the issue which we discussed in the previous section - whether our model does not overfit or undeerfit. In case of our canteen, this would mean that we train the model on the first 4 months of the labelled data. We then use the most recent month to evaluate and judge whether our model does not underfit or overfit. If our conclusion is that it doesn’t, we can use it to make predictions for our unlabelled data (tomorrow) and be sure that the predictions made by model will be accurate.</p>
<p>What would it mean if our canteen model is underfitted or overfitted? How would we know? In upcoming sections you are going to learn numerical and exact techniques of how to do this, but for now we need to stick to logic and intuition.</p>
<p>We said that if model is <strong>overfitted</strong>, it is great at describing training data, but poor at describing unseen data. When we fitted the model, we saw that it is making great predictions about the first four months of our meal consumption. In most of the days, it can really pinpoint the exact amount of meals which were consumed. For instance, when we made Spaghetti Carbonara, the model correctly predicted that 187 portions are going to be consumed. That sounds amazing! We use the model to make predictions for the most recent month, during which we one day cooked Spaghetti Bolognese, which are just different alternations of Spaghetti. We hence presume that our model will be again great. To our surprise, it predicts that 190 meals will be consumed, while in reality we sell only 110 meals. Our model is overfitted and failed to generalize to unseen (validation) data. We hence know that we cannot use it to predict our unlabelled data (tomorrow).</p>
<p>We defined <strong>underfitted</strong> model as one which is poor at describing <em>both</em> training and unseen data. This one will be hence even easier to spot. When we cooked Spaghetti Carbonara, it predicted 130 meals, while really 187 meals were consumed. In the last month, which the model did not see, when we cooked Spaghetti Bolognese, the prediction by the model was 143 meals, while we really sold 110 meals. We can see that the model was poor at describing both of these meals.</p>
</div>
<div id="regression" class="section level2">
<h2><span class="header-section-number">3.12</span> Regression</h2>
<p><em>What is regression?</em> It is now time that we expand our Machine Learning mind map. Supervised learning has several subfields, which are influenced by the form of our target feature. At this level, we are going to learn about regression and binary classification. Let’s start with <strong>regression</strong>.</p>
<div class="figure"><span id="fig:machine-learning-areas-2"></span>
<img src="resources/02-observer/machine-learning-areas-2.png" alt="First area of Supervised Learning that we will focus on is Regression." width="359" />
<p class="caption">
Figure 3.28: First area of Supervised Learning that we will focus on is Regression.
</p>
</div>
<p>In <em>regression supervised learning</em> our target variable is of numerical form. Here are some examples of numerical target features:</p>
<ul>
<li>Predicting <strong>income</strong> of a person. Values can be any numeric larger than 0 Euro, such as 580 Euro, 1561.6 Euro.</li>
<li>Predicting <strong>cooling time</strong> of iron during the forging process. Values can be any numeric larger than 0 minutes, such as 6 minutes or 257 minutes.</li>
<li>Predicting <strong>weight change</strong> of adults over a period of one year of weight loss process. Values can be any numeric in range -30 Kilograms (Wau) to +30 Kilograms (Uhh).</li>
</ul>
<p>The way Machine Learning model which should be of <em>supervised regression type</em> is going to be built exactly as we discussed. We have a set of independent features, and our target feature. Let’s now build some really simple regression model.</p>
<p>We are a real estate agent, selling houses in the suburbs of Stockholm. One of the really difficult things in our job is to evaluate what the property is worth and how much a potential buyer will be willing to pay for the property. We currently have only <em>gut feeling</em> and some rules which we developed over the past years of this job. Here is how we could evaluate price now:</p>
<ul>
<li>Largest factor that determines the price of a house is the inhabitable area. Price per square meter starts at 1000 Euro. Thus if the house has 100 square meters, we estimate that its price will be 100 000 Euro.</li>
<li>If the house is nearby a lake or coast, the price increases.</li>
<li>If the house is renovated in the past 10 years, or built within the past 10 years, its price will be higher.</li>
</ul>
<p>We can start building a <strong>regression model</strong> with a single independent feature only (to make it simple), which will be the living area of a house. As we discussed we start with <strong>training data</strong>. To obtain these, we look at the historical sales of houses in the area. We make a simple plot, which shows how the area of a house and the house’s final sale price worked in the past.</p>
<p>This confirms our past experience, that the price of a house will be heavily determined by the living area. Our task is now to <strong>train the model</strong>. You will learn technical details of how to do this in the upcoming chapter (Contributor), we now only need to understand the logic. The trained regression model will attempt to fit a line, which will describe our training data well.</p>
<p>Once the model is trained, we can forget our training data and are left only with <strong>trained model</strong>. In the picture below, this is represented by our regression line.</p>
<p>We can now use this model to predict for us a price of a house, based on the provided living area. The living area of our house of interest has a living area of 80 square metres. We look at our horizontal axis and find a value of our independent feature - 80. We now draw a vertical line up and wait until it intersects with our regression line. That is the <strong>prediction of our model</strong>. The only thing we have to do now is that we draw a horizontal line to the left and read out the predicted price for this house. In this case, 67500 Euro.</p>
<div class="figure"><span id="fig:mapping-regression"></span>
<img src="resources/02-observer/mapping-regression.jpg" alt="By inputting a value of our independent feature into regression model, we obtain its prediction."  />
<p class="caption">
Figure 3.29: By inputting a value of our independent feature into regression model, we obtain its prediction.
</p>
</div>
<p>We can replicate this process on our dataset.</p>
<p>We have now managed to fit a <strong>regression</strong>. In case you are headed to the more advanced levels, such as Contributor, you are going to learn exact techniques of how this is done, but as I said, on this level it is sufficient if you are aware of the conceptual steps when fitting a regression model. As we mentioned, the price of a house is of course determined by many more factors. In the upcoming chapters, we will also construct a detailed elaboration on this example of predicting house prices.</p>
<p><em>How do I know if a regression model is good?</em></p>
<p>As an Observer, you need to be able to do a basic evaluation of a regression model, when you see one. You are not supposed to calculate it yourself, just observe it. The most basic evaluation of a regression model is through <strong>average error</strong>. How is this error calculated?</p>
<blockquote>
<p>Average error of a regression model is a bare sum of all the single errors the regression model makes, divided by number of observations. Single error is calculated as a difference between prediction and actual value.</p>
</blockquote>
<p>This definition contains a few new things, so let’s take it step by step. We have trained our model on <em>training data</em> and we want it to make prediction on <em>unlabelled data</em>. We have though already mentioned that part of our training data will be put aside and used as <em>validation data</em>. This is a dataset that we will use to calculate the average error of our regression model.</p>
<p><strong>Single error</strong> is what we obtain first. We take one house from our validation data and let the model make a prediction for this house. The prediction is going to say that this house will be sold for 87 000 Euro. As we know the actual sale price for which this house has been sold, we can <strong>compare the predicted value, with actual value</strong> for which this house was sold - 92 000 Euro.</p>
<div class="figure"><span id="fig:single-error"></span>
<img src="resources/02-observer/single-error.jpg" alt="Single error (on one observation) is obtained by taking the difference between actual and predicted value."  />
<p class="caption">
Figure 3.30: Single error (on one observation) is obtained by taking the difference between actual and predicted value.
</p>
</div>
<p>The very same procedure we now do for all houses which we are making predictions for.</p>
<div class="figure"><span id="fig:all-errors"></span>
<img src="resources/02-observer/all-errors.jpg" alt="We repeat the same procedure and obtain a single error from all observations."  />
<p class="caption">
Figure 3.31: We repeat the same procedure and obtain a single error from all observations.
</p>
</div>
<p>All that we now need to do is to calculate the average out of these errors. To calculate an average error, we only need to sum all of the errors made by the model and divide by number of observations. There is a small trick though. Some of the errors have negative and some have positive sign, as they were obtained using same calculation <strong>actual value - predicted value</strong>.</p>
<ul>
<li>If actual value is higher (80 000 Euro) than predicted value (67 500 Euro), the resulting single error will be positive (13 500 Euro).</li>
<li>If actual value is lower (50 000 Euro) than predicted value (57 500 Euro), the resulting single error will be negative (-7 500 Euro).</li>
</ul>
<p>If we would now sum them all up, it would be a terrible mistake as negative errors would be cancelling out with positive errors such as: 13 500 + (-7500) = 6000 Euro. What Data Scientist usually does is that he/she uses squaring to the power of two and then using square root. This removes all the negative signs and we can happily sum up together all the errors to calculate the average error. That is why when you will see a Machine Learning regression model reporting its accuracy oftentimes say something like root-mean-squared-error (rmse). All that is happening here is that we are calculating mean-error, we just need to get rid of the negative signs.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Let&#39;s sum together all single errors which we did (gotten rid of negative signs).</span>
sum_of_errors =<span class="st"> </span><span class="dv">13500</span> <span class="op">+</span><span class="st"> </span><span class="dv">7500</span> <span class="op">+</span><span class="st"> </span><span class="dv">5000</span> <span class="op">+</span><span class="st"> </span><span class="dv">850</span> <span class="op">+</span><span class="st"> </span><span class="dv">12000</span> <span class="op">+</span><span class="st"> </span><span class="dv">3500</span>
<span class="co">#Now we calculate the mean (average) error by simply dividing by the total number of houses which we are evaluating.</span>
mean_error =<span class="st"> </span>sum_of_errors <span class="op">/</span><span class="st"> </span><span class="dv">6</span>

<span class="kw">print</span>(mean_error)</code></pre></div>
<pre><code>## [1] 7058.333</code></pre>
<p>As you can see, from a numerical perspective, it is rather simple to evaluate how successful regression is. We can simply calculate the <em>root-mean-squared-error</em> which will already give us a solid estimate. In our case, this was 7058 Euro, which seems fine. Our model is far from perfect, but it can quickly give us an estimation of what the house is worth. Unfortunately we need to be a bit more careful, let’s again look at our predictions and actual values.</p>
<div class="figure"><span id="fig:lucrative-houses"></span>
<img src="resources/02-observer/lucrative-houses.jpg" alt="We repeat the same procedure and obtain a single error from all observations."  />
<p class="caption">
Figure 3.32: We repeat the same procedure and obtain a single error from all observations.
</p>
</div>
<p>Sometimes, the overall view on the error, such as absolute error or average error can be rather misleading. If you noticed, three of the most expensive houses have been heavily <strong>underpriced by the model</strong>. This is caused simply by the fact that our regression model is not equally good at all levels of house prices. Now from a context perspective, this can be a big issue as we are underpricing the most lucrative houses! Our lucrative clients can get pretty unhappy about that.</p>
</div>
<div id="classification" class="section level2">
<h2><span class="header-section-number">3.13</span> Classification</h2>
<p><em>What is binary classification?</em></p>
<p>We can now move to <em>binary classification</em>, which is a supervised model, where the target feature can have only two values. These two values can have various forms:</p>
<p><em>True, False </em>Buy, No-Buy <em>Will run through, Will not run through </em>Healthy, Not healthy</p>
<div class="figure"><span id="fig:machine-learning-areas-3"></span>
<img src="resources/02-observer/machine-learning-areas-3.png" alt="Second are of Supervised learning that we will go through is Binary Classification." width="358" />
<p class="caption">
Figure 3.33: Second are of Supervised learning that we will go through is Binary Classification.
</p>
</div>
<p><em>How do I evaluate if the classification model is good?</em></p>
<p>Discuss imbalanced classification issue.</p>
<p>Discuss confusion matrix and predicting what actually matters for us.</p>
</div>
<div id="level-2-reached" class="section level2">
<h2><span class="header-section-number">3.14</span> Level 2 Reached</h2>
<p>Congratulations! You have just reached level 2 - Observer. You are now able to join a Data Science initiative around you - it can be some public project, pro-bono project, or a project which is being developed inside your company. Moreover, if you are applying for a position related to Data Science, you can claim that you are on the Observer Level. This means that you know what is going on within the project, and you should be able to help with inputs, outputs, and do some basic evaluations of the project.</p>
<p>Here are some key takeaways from this chapter:</p>
<ul>
<li>Always remain skeptical about whether your data can even answer the problem which you are trying to solve.</li>
<li>Try to avoid using self-reported (human-related data) as these can be a subject to heavy biases.</li>
<li>Remember that the Data Science project tries to explain the phenomena through observations and their features (characteristics).</li>
<li>Simplest form of representing data is through a flat table, in a csv format.</li>
<li>If we have data of different granularity, we might want to use a concept of relational database to represent these properly.</li>
<li>Data can be loaded into an environment which can help us with processing of it. These vary from ones which are programming heavy - R and Python, to some which are more visual, but can be less flexible, such as Knime.</li>
<li>Machine Learning might be a hearth of Data Science. We train a model using training data, validate its predictive power on validation data and then use it for predicting unlabelled data.</li>
<li>Be aware of not overfitting or underfitting of your model.</li>
<li>Regression is a field of Supervised Learning, where our target feature is of numeric kind. We evaluate its success through measures such as root-mean-squared-error, though we are carefully looking at the single errors and their contextual meaning.</li>
<li>Binary Classification is another field of Supervised Learning, where our target feature only has two values. We evaluate its success through measures such as Recall, Precision or Accuracy. We thought carefully to look at the confusion matrix.</li>
</ul>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="being-aware.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="contributor-I.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["intuitive-ds-book.pdf", "intuitive-ds-book.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
